// //Class method 
// import { User } from "../models/User.model"; //User model to talk to MongoDB
// import  jwt  from "jsonwebtoken";  // to generate JWT token
// import { ISignupBody, ILoginBody } from "../types/auth.types";

// export class AuthService {

//     //SIGNUP
//     async signup(data: ISignupBody){
//         const {name, email, password}= data;  // destructure data from controller

//         //1. check if user already exist
//         const existingUser= await User.findOne({email});
//         if(existingUser){
//             throw new Error("Email already registered"); // stops execution, goes to catch in controller
//         }

//         // 2. create user in MongoDB
//     // password gets hashed automatically by pre-save hook in User.model.ts
//         const user= await User.create({name, email, password});

//         //3. generate JWT token
//         const token= this.generateToken(user._id.toString(), user.email);

//         return {
//             token, // JWT token generated by generateToken()
//             user:{
//                 id: user._id.toString(), // MongoDB auto generated _id → converted to string
//                 name: user.name,  // user's name saved in MongoDB
//                 email: user.email, // user's email saved in MongoDB
//             },
//         };
//     }

//     //LOGIN 
//     async login(data: ILoginBody){
//         const {email, password}= data;  // destructure data from controller

//         //1. finder user by email
//         const user= await User.findOne({email});
//         if(!user){
//             throw new Error("Invalid email or password");//⚠️ don't say "email not found" — security risk 
//         }

//           // 2. compare entered password with hashed password in MongoDB
//         const isMatch=  await user.comparePassword(password);
//         if (!isMatch){
//             throw new Error("Invalid email or password");
//         }

//         //3. generate JWT token
//         const token= this.generateToken(user._id.toString(), user.email);

//         // 4. return token + user info to controller
//         return {
//             token, 
//             user:{
//                 id: user._id.toString(),
//                 name: user.name,
//                 email:user.email,
//             },
//         };
//     }

//     // GENERATE TOKEN (private helper)
//     private generateToken(userId: string, email:string):string{
//         const payload= {userId, email};
//         const secret= process.env.JWT_SECRET!;
//         const token= jwt.sign(payload, secret, {expiresIn: "7d"});
//         return token;
//     }
// }

// export const authService= new AuthService();





//Function 
import {User} from "../models/User.model";
import jwt from "jsonwebtoken";
import {ISignupBody, ILoginBody} from "../types/auth.types";

//HELPER FUNCTION - To generate jwt token
//only used inside this file, so not exported
const generateToken= (userId: string, email: string): string=>{
    const payload= {userId, email};
    const secret= process.env.JWT_SECRET!;
    const token=jwt.sign(payload, secret, {expiresIn: "7d"});
    return token;
}

// SIGNUP FUNCTION
export const Ssignup= async (data: ISignupBody)=>{
    const {name, email, password}= data;

    //1. check if user already exist
    const existingUser= await User.findOne({email});
    if(existingUser){
        throw new Error("Email already registered");
    }

    //2. create user in MongoDB
    const user= await User.create({name, email, password});

    //3. generate JWT token
    const token= generateToken(user._id.toString(), user.email);

    //4. return token + user info to controller
    return {
        token, 
        user:{
            id: user._id.toString(),
            name: user.name,
            email: user.email,
        },
    };
};

//LOGIN FUNCTION
export const Slogin= async (data: ILoginBody)=>{
    const {email, password}= data;

    //1. find user by email
    const user= await User.findOne({email});
    if(!user){
        throw new Error("Invalid email or password");
    }

    //2.compare entered password with hashed password in MongoDB
    const isMatch= await user.comparePassword(password);
    if(!isMatch){
        throw new Error("Invalid email or password");
    }

    //3. generate jwt token
    const token= generateToken(user._id.toString(),user.email);

    //4. return token + user info to controller
    return {
        token, 
        user:{
            id: user._id.toString(),
            name: user.name,
            email:user.email,
        },
    };
};
